export const WALLET_ADDRESS = process.env.REACT_APP_BAOBAB_WALLET_ADDRESS
export const CONTRACT_ADDRESS =  process.env.REACT_APP_BAOBAB_CONTRACT_ADDRESS
export const ACCESS_KEY_ID =  process.env.REACT_APP_BAOBAB_ACCESS_KEY_ID
export const SECRET_ACCESS_KEY =  process.env.REACT_APP_BAOBAB_SECRET_ACCESS_KEY
export const CHAIN_ID = "1001" // MAINNET 8217 TESTNET 1001'
